import type { BuiltinPlugin } from "../../../../shared/remotePlugins";

/**
 * The plugins that ship with the build.
 *
 * Committed content, like the command catalog — nothing here is fetched at runtime. Each skill's
 * body is the whole `SKILL.md`; installing a plugin writes these through `writeResource`, the same
 * path a hand-written skill takes. Skill names are ASCII (they become directory names) and unique
 * across every plugin.
 *
 * **Two audiences, one file.** A skill's `body` is read by the model, and the prompt is one
 * document in one language, so bodies stay in English. Everything else here — the plugin's name and
 * summary, each skill's description, and every starter — is read by the operator, so the window
 * puts it through `t()` as it draws it. That is why `i18n.test.ts` walks this list: a plugin added
 * without translations fails the build rather than showing English on a Japanese screen.
 *
 * A starter's `goal` belongs to the operator too, not to the model: it lands in the message box to
 * be read and edited before it is sent.
 *
 * The bodies are arrays of lines joined at read time rather than template literals, because a
 * SKILL.md is full of `backtick`-quoted commands and a template literal would need every one of
 * them escaped. Same shape as `template()` in resources.ts.
 */

const md = (lines: string[]) => lines.join("\n");

export const PLUGINS: BuiltinPlugin[] = [
  {
    id: "discover",
    name: "Unfamiliar server",
    summary:
      "How to work out what a server runs and where it keeps it, without knowing the distribution, the layout, or whether anything was installed by hand.",
    /* Matches the OS names a facts summary carries, so it is offered on any Linux machine. */
    stack: ["ubuntu", "debian", "centos", "rocky", "alma", "rhel", "red hat", "amazon", "suse", "linux"],
    skills: [
      {
        name: "unfamiliar-server",
        goal:
          "Work out what this server runs and where its configuration lives. Start from what is listening and what owns those sockets, ask each binary where its own configuration is, and check the service manager and the package manager. Do not assume a distribution layout. Tell me what you could not read and why.",
        description:
          "Finding a server's configuration without guessing paths: ask the socket, the binary, the service manager and the package manager, in that order, and search the filesystem last.",
        body: md([
          "---",
          "name: unfamiliar-server",
          "description: Finding a server's configuration without guessing paths: ask the socket, the binary, the service manager and the package manager, in that order, and search the filesystem last.",
          "goal: Work out what this server runs and where its configuration lives. Start from what is listening and what owns those sockets, ask each binary where its own configuration is, and check the service manager and the package manager. Do not assume a distribution layout. Tell me what you could not read and why.",
          "---",
          "",
          "# Working out how an unfamiliar server is put together",
          "",
          "**Never guess a path. Ask the thing that is running.**",
          "",
          "`/etc/apache2` is Debian. `/etc/httpd` is RHEL. Neither is right for a build from source",
          "in `/usr/local`, or for a container, or for whatever the last contractor did. Every step",
          "below asks the machine instead, and each answer rules out work you would otherwise do.",
          "",
          "## 1. What is listening, and what owns it",
          "",
          "```",
          "ss -tulpnH      # every TCP/UDP socket — do not filter by port number",
          "ss -xlpH        # unix sockets: php-fpm often has no TCP port at all",
          "ps -eo pid,user,comm,args   # things that listen for nothing: workers, cron jobs",
          "```",
          "",
          "Port 80 and 3306 being open does not mean \"WordPress and its database\". The port a",
          "service uses is a convention, not a fact, and the database this site uses may not be on",
          "this machine at all.",
          "",
          "## 2. Ask the process and the binary where they live",
          "",
          "```",
          "readlink /proc/<pid>/exe                 # the real binary",
          "tr '\\0' ' ' < /proc/<pid>/cmdline        # -c / -f / --defaults-file are usually here",
          "ls -l /proc/<pid>/fd/                    # the log files it has open right now",
          "```",
          "",
          "`/proc/<pid>/fd` is the answer to \"where is the log\": it is whatever the process has",
          "open, whatever the distribution calls it. Other people's processes need privilege; when",
          "it is refused, say so and use the next step.",
          "",
          "Programs will also state their own layout, source build or not:",
          "",
          "```",
          "apache2ctl -V   apachectl -V   httpd -V    # HTTPD_ROOT and SERVER_CONFIG_FILE",
          "apache2ctl -S                              # every vhost: its file:line and DocumentRoot",
          "nginx -V                                   # --prefix --conf-path --error-log-path",
          "nginx -T                                   # the effective config, all includes resolved",
          "php --ini      php -v      php-fpm -t",
          "mysqld --help  mariadbd --help             # which my.cnf files are read, in order",
          "postgres -C config_file",
          "```",
          "",
          "## 3. What the service manager was told",
          "",
          "```",
          "systemctl show <unit> -p FragmentPath,ExecStart,Environment,WorkingDirectory,User",
          "systemctl cat <unit>          # the unit file and its drop-ins",
          "journalctl -u <unit>          # the log, without knowing any path at all",
          "```",
          "",
          "`journalctl -u` is the one reading that is the same sentence on every distribution.",
          "Prefer it over hunting for a file.",
          "",
          "## 4. What the package manager placed — and what was changed",
          "",
          "```",
          "dpkg -S <path>    rpm -qf <path>     # which package owns this file",
          "dpkg -L <pkg>     rpm -ql <pkg>      # everything that package placed",
          "debsums -c        rpm -Va            # which files differ from what was shipped",
          "```",
          "",
          "The last line is the valuable one on a machine nobody documented: **the files somebody",
          "changed are the interesting files**, and everything else is the distribution's default.",
          "",
          "If nothing owns the binary, it was built or unpacked by hand. Stop applying distribution",
          "layouts and go to step 5.",
          "",
          "## 5. Search the filesystem — last, and bounded",
          "",
          "```",
          "locate -b wp-config.php                    # instant, if the machine keeps an index",
          "ls -la /usr/local /opt /srv /data /var/www  # where hand-installed things actually live",
          "find /usr/local /opt -name httpd.conf      # bounded roots, not /",
          "grep -rlI -m1 -e '<VirtualHost' -e DocumentRoot /etc /usr/local /opt",
          "```",
          "",
          "Search by **content** when the name is unknown: a config file names itself.",
          "",
          "A walk from `/` stops for the operator, and it should: on a machine with a network mount",
          "it can take an hour and slow down whatever that server is for. If you truly need one,",
          "say why, and use `-xdev` so it stays on one filesystem.",
          "",
          "## What each answer rules out",
          "",
          "| Answer | What to stop doing |",
          "| --- | --- |",
          "| The binary belongs to no package | Forget `/etc/apache2` and `/etc/httpd` |",
          "| `-S` shows several vhosts | \"The site\" is ambiguous — ask the operator which one |",
          "| `DB_HOST` is not local | The database is on another machine; stop reading this one's |",
          "| No unit for it | Started by rc.local, `@reboot`, supervisord, or a container |",
          "",
          "## Containers",
          "",
          "```",
          "docker inspect <name> --format '{{json .Mounts}} {{.LogPath}} {{json .Config.Env}}'",
          "```",
          "",
          "Mounts say which host path is which path inside. Configuration you can edit lives on the",
          "host side of a mount; anything else is baked into the image and changing it is a rebuild.",
          "",
          "## Credentials",
          "",
          "Configuration files hold passwords. Values that look like credentials are removed from",
          "command output before it reaches you — the key is left so you can see that a password is",
          "set and what it is for. That is deliberate. Do not try to work around it, and never copy",
          "a credential into a summary, a handover or a report.",
          "",
        ]),
      },
      {
        name: "find-server-logs",
        description:
          "Per-unit journals and the files the daemons have open",
        goal:
          "Find the logs for the services running on this server. Prefer the per-unit journal over hunting for files, and check what the running processes actually have open. Tell me which ones you cannot read.",
        body: md([
          "---",
          "name: find-server-logs",
          "description: Per-unit journals and the files the daemons have open",
          "goal: Find the logs for the services running on this server. Prefer the per-unit journal over hunting for files, and check what the running processes actually have open. Tell me which ones you cannot read.",
          "---",
          "",
          "# Per-unit journals and the files the daemons have open",
          "",
          "Read the `unfamiliar-server` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Find the logs for the services running on this server. Prefer the per-unit journal over hunting for files, and check what the running processes actually have open. Tell me which ones you cannot read.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "find-changed-config",
        description:
          "The files somebody edited are the interesting ones",
        goal:
          "Find which configuration files on this server differ from what their packages shipped, and show me the ones that look deliberate. Anything not owned by a package is worth naming too.",
        body: md([
          "---",
          "name: find-changed-config",
          "description: The files somebody edited are the interesting ones",
          "goal: Find which configuration files on this server differ from what their packages shipped, and show me the ones that look deliberate. Anything not owned by a package is worth naming too.",
          "---",
          "",
          "# The files somebody edited are the interesting ones",
          "",
          "Read the `unfamiliar-server` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Find which configuration files on this server differ from what their packages shipped, and show me the ones that look deliberate. Anything not owned by a package is worth naming too.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
    ],
  },

  {
    id: "lamp",
    name: "LAMP (WordPress, Apache, MySQL)",
    summary:
      "When a website is down, slow, or throwing errors: how to work through Apache, MySQL and WordPress.",
    stack: ["apache", "apache2", "httpd", "mysql", "mariadb", "mysqld", "wordpress", "wp-", "php", "php-fpm"],
    skills: [
      {
        name: "lamp",
        description:
          "Investigating Apache, MySQL and WordPress: where the logs are, how to get at 4xx/5xx, and how to look at a slow page and its database.",
        body: md([
          "---",
          "name: lamp",
          "description: Investigating Apache, MySQL and WordPress: where the logs are, how to get at 4xx/5xx, and how to look at a slow page and its database.",
          "---",
          "",
          "# Investigating a LAMP server (Apache, MySQL, WordPress)",
          "",
          "Where to look first when someone says a site is down, slow, or throwing errors.",
          "",
          "## Start by finding out how this machine is put together",
          "",
          "**Service names and log paths differ from machine to machine.** Apache answers to both",
          "`apache2` and `httpd`; its log is written to `/var/log/apache2/error.log`, or to",
          "`/var/log/httpd/error_log`, or to a per-site `/var/www/…/logs/`, or to",
          "`/usr/local/apache2/logs/`. Do not go looking in a place you picked in advance.",
          "",
          "The `unfamiliar-server` skill has the order for finding out rather than guessing: what is",
          "listening → the process's `/proc/<pid>/fd` → `apache2ctl -V`/`-S` and `nginx -T` → the",
          "unit → the package → and the filesystem last. **On a server you do not know, read that",
          "first.**",
          "",
          "Three things to pin down here:",
          "- What is running and what it is listening on (`ss -tulpnH`,",
          "  `systemctl list-units --type=service`)",
          "- The web server's configuration root and its vhosts (`apache2ctl -S` / `apachectl -S` /",
          "  `nginx -T`)",
          "- Whether it answers at all (`curl -sI http://localhost/` — the status line only)",
          "",
          "## Getting to the log",
          "- **`journalctl -u <unit>` first.** No path needed, and the same on every distribution.",
          "- If you need the file, use the one the configuration names (the ErrorLog in",
          "  `apache2ctl -S`, the `access_log`/`error_log` in `nginx -T`). It may be per-site.",
          "- What the running process has open is the surest answer: `ls -l /proc/<pid>/fd/`",
          "  (needs privilege).",
          "",
          "## Looking into 4xx/5xx (and handling a large log)",
          "An access log is large. Never read the whole thing into this conversation.",
          "1. Get a rough hold of it on the server: `tail -n 200 <access.log>`,",
          "   `grep ' 500 ' <access.log> | tail`",
          "2. If you need counts, copy the log across and total it up here (fetch_log to copy,",
          "   run_local for awk/sort/uniq — pipes cannot be used on the server). Counts by status,",
          "   the busiest URLs, which hours.",
          "3. For a 5xx, line up error.log against the PHP-FPM and MySQL errors. For a 4xx, look at",
          "   which URL and which referrer.",
          "",
          "## When it is slow",
          "- Load: `uptime`, `top -bn1 | head -20`",
          "- Work out which of Apache, PHP-FPM and MySQL is eating the machine",
          "- MySQL: `mysqladmin status`, and `mysqladmin processlist` while it is happening (ask the",
          "  operator if it needs credentials)",
          "",
          "## WordPress",
          "- Configuration: `wp-config.php`. **Follow the DocumentRoot from `apache2ctl -S` to find",
          "  it** — it is not always `/var/www/html`.",
          "- Always look at `DB_HOST`. **It is not always localhost** — if it is another host, no",
          "  amount of looking at this machine's MySQL is relevant, and the investigation moves.",
          "- Passwords and authentication keys are hidden before they reach you. Do not try to work",
          "  around that, and **never copy one into a summary, a handover or a report**.",
          "- Common causes: a PHP error from a plugin or theme (error.log), the database connection",
          "  dropping, permissions, a rewritten .htaccess, caching.",
          "",
          "## Before changing anything",
          "- Establish the state before you change it. To edit a setting, read the file first and",
          "  show what would change.",
          "- Say what a service restart affects before you do it. Before stopping or disabling",
          "  something, make sure it can be undone.",
          "",
        ]),
      },
      {
        name: "lamp-errors",
        description:
          "From the access and error logs: when, which URL, and how many",
        goal:
          "Look into the Apache, PHP-FPM and MySQL errors and get a first idea of what is behind the recent 5xx/4xx. Start from whether the services are alive and what the latest log lines say, and if you need counts, copy the large logs across and total them up here. Do not copy out settings or passwords.",
        body: md([
          "---",
          "name: lamp-errors",
          "description: From the access and error logs: when, which URL, and how many",
          "goal: Look into the Apache, PHP-FPM and MySQL errors and get a first idea of what is behind the recent 5xx/4xx. Start from whether the services are alive and what the latest log lines say, and if you need counts, copy the large logs across and total them up here. Do not copy out settings or passwords.",
          "---",
          "",
          "# From the access and error logs: when, which URL, and how many",
          "",
          "Read the `lamp` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Look into the Apache, PHP-FPM and MySQL errors and get a first idea of what is behind the recent 5xx/4xx. Start from whether the services are alive and what the latest log lines say, and if you need counts, copy the large logs across and total them up here. Do not copy out settings or passwords.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "lamp-slow",
        description:
          "Narrow it down from load, processes and MySQL's state",
        goal:
          "Find out why the site is answering slowly. Start with the load and which of Apache, PHP-FPM and MySQL is eating the machine, then get a first idea of which pages or queries are slow.",
        body: md([
          "---",
          "name: lamp-slow",
          "description: Narrow it down from load, processes and MySQL's state",
          "goal: Find out why the site is answering slowly. Start with the load and which of Apache, PHP-FPM and MySQL is eating the machine, then get a first idea of which pages or queries are slow.",
          "---",
          "",
          "# Narrow it down from load, processes and MySQL's state",
          "",
          "Read the `lamp` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Find out why the site is answering slowly. Start with the load and which of Apache, PHP-FPM and MySQL is eating the machine, then get a first idea of which pages or queries are slow.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "lamp-services",
        description:
          "Apache, MySQL and PHP-FPM: alive, and any recent crash",
        goal:
          "Check whether Apache, MySQL (or MariaDB) and PHP-FPM are alive and whether any of them has crashed or restarted recently, and if something is wrong, get a first idea of why.",
        body: md([
          "---",
          "name: lamp-services",
          "description: Apache, MySQL and PHP-FPM: alive, and any recent crash",
          "goal: Check whether Apache, MySQL (or MariaDB) and PHP-FPM are alive and whether any of them has crashed or restarted recently, and if something is wrong, get a first idea of why.",
          "---",
          "",
          "# Apache, MySQL and PHP-FPM: alive, and any recent crash",
          "",
          "Read the `lamp` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Check whether Apache, MySQL (or MariaDB) and PHP-FPM are alive and whether any of them has crashed or restarted recently, and if something is wrong, get a first idea of why.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "lamp-wordpress",
        description:
          "wp-config and plugin errors (secrets stay hidden)",
        goal:
          "Check how WordPress is configured. Look at the settings in wp-config (which database it talks to, debugging, caching) and at the PHP errors from plugins and themes in error.log. You may read passwords and authentication keys, but do not copy them out.",
        body: md([
          "---",
          "name: lamp-wordpress",
          "description: wp-config and plugin errors (secrets stay hidden)",
          "goal: Check how WordPress is configured. Look at the settings in wp-config (which database it talks to, debugging, caching) and at the PHP errors from plugins and themes in error.log. You may read passwords and authentication keys, but do not copy them out.",
          "---",
          "",
          "# wp-config and plugin errors (secrets stay hidden)",
          "",
          "Read the `lamp` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Check how WordPress is configured. Look at the settings in wp-config (which database it talks to, debugging, caching) and at the PHP errors from plugins and themes in error.log. You may read passwords and authentication keys, but do not copy them out.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
    ],
  },

  {
    id: "nginx",
    name: "Nginx (web server, reverse proxy)",
    summary:
      "Nginx returning 502/504, a setting that has no effect, an expired certificate — where to look.",
    stack: ["nginx"],
    skills: [
      {
        name: "nginx",
        description:
          "Investigating Nginx: checking the configuration (nginx -t), looking upstream for a 502/504, the access and error logs, and certificate expiry.",
        body: md([
          "---",
          "name: nginx",
          "description: Investigating Nginx: checking the configuration (nginx -t), looking upstream for a 502/504, the access and error logs, and certificate expiry.",
          "---",
          "",
          "# Investigating Nginx (web server, reverse proxy)",
          "",
          "## Start with",
          "- Alive: `systemctl status nginx`",
          "- Configuration valid: `nginx -t` (catches syntax and path mistakes here — **always",
          "  before a reload**)",
          "- Answering: `curl -sI http://localhost/`",
          "",
          "## Logs",
          "- `/var/log/nginx/access.log` and `/var/log/nginx/error.log` (they may be split per site)",
          "- Never read a large log in full. Narrow it with tail/grep, and if you need counts, copy",
          "  it across and total it up with run_local.",
          "",
          "## 502 / 504 (upstream is not answering)",
          "Usually it is not Nginx but what is behind it — PHP-FPM, the application, another server.",
          "1. error.log at that moment: the `upstream` line gives the reason (connection refused /",
          "   timed out).",
          "2. Is the upstream alive: for PHP-FPM, `systemctl status php*-fpm` and its socket; for an",
          "   application, its port.",
          "3. A timeout points at a slow upstream. A refused connection means it is down, or the",
          "   port is wrong.",
          "",
          "## Configuration",
          "- What is actually in effect: `nginx -T` (capital T, every include resolved — it is large,",
          "  so read only the server block you need)",
          "- Work out which server_name and location a request matches, from its Host and path.",
          "",
          "## Certificates",
          "- Expiry: `openssl x509 -enddate -noout -in <certificate>`, or the certificate lines from",
          "  `curl -vI https://host/`.",
          "- Expired, an incomplete chain, or a name that does not match are the usual causes.",
          "",
          "## Before changing anything",
          "- `reload` only after `nginx -t` passes. Consider `reload` before `restart`.",
          "- To edit a setting, read the file first and show what would change.",
          "",
        ]),
      },
      {
        name: "nginx-502",
        description:
          "Narrow it down from error.log and whether the upstream is alive",
        goal:
          "Look into why Nginx is returning 502/504. Read the upstream lines in error.log and get a first idea of whether the PHP-FPM or application behind it is down or timing out.",
        body: md([
          "---",
          "name: nginx-502",
          "description: Narrow it down from error.log and whether the upstream is alive",
          "goal: Look into why Nginx is returning 502/504. Read the upstream lines in error.log and get a first idea of whether the PHP-FPM or application behind it is down or timing out.",
          "---",
          "",
          "# Narrow it down from error.log and whether the upstream is alive",
          "",
          "Read the `nginx` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Look into why Nginx is returning 502/504. Read the upstream lines in error.log and get a first idea of whether the PHP-FPM or application behind it is down or timing out.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "nginx-config",
        description:
          "nginx -t, and what is actually in effect",
        goal:
          "Check the Nginx configuration. Start with nginx -t for validity, then work out which server and location the Host and path in question actually match.",
        body: md([
          "---",
          "name: nginx-config",
          "description: nginx -t, and what is actually in effect",
          "goal: Check the Nginx configuration. Start with nginx -t for validity, then work out which server and location the Host and path in question actually match.",
          "---",
          "",
          "# nginx -t, and what is actually in effect",
          "",
          "Read the `nginx` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Check the Nginx configuration. Start with nginx -t for validity, then work out which server and location the Host and path in question actually match.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "nginx-certificate",
        description:
          "TLS expiry, the chain, and whether the name matches",
        goal:
          "Check when the TLS certificate this Nginx uses expires, and whether there is anything wrong with its chain or with the name it is issued for.",
        body: md([
          "---",
          "name: nginx-certificate",
          "description: TLS expiry, the chain, and whether the name matches",
          "goal: Check when the TLS certificate this Nginx uses expires, and whether there is anything wrong with its chain or with the name it is issued for.",
          "---",
          "",
          "# TLS expiry, the chain, and whether the name matches",
          "",
          "Read the `nginx` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Check when the TLS certificate this Nginx uses expires, and whether there is anything wrong with its chain or with the name it is issued for.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "nginx-access-log",
        description:
          "Counts by status and by URL, to see what stands out",
        goal:
          "From the Nginx access log, get the shape of the traffic by status and by URL, and find anything that stands out. Copy large logs across and total them up here.",
        body: md([
          "---",
          "name: nginx-access-log",
          "description: Counts by status and by URL, to see what stands out",
          "goal: From the Nginx access log, get the shape of the traffic by status and by URL, and find anything that stands out. Copy large logs across and total them up here.",
          "---",
          "",
          "# Counts by status and by URL, to see what stands out",
          "",
          "Read the `nginx` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> From the Nginx access log, get the shape of the traffic by status and by URL, and find anything that stands out. Copy large logs across and total them up here.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
    ],
  },

  {
    id: "docker",
    name: "Docker (containers, Compose)",
    summary:
      "A container that dies, restarts in a loop, or eats the disk — where to look in a container setup.",
    stack: ["docker", "containerd", "compose"],
    skills: [
      {
        name: "docker",
        description:
          "Investigating Docker and Compose: whether containers are alive and restarting, following their logs, resources and disk, and reading a Compose setup.",
        body: md([
          "---",
          "name: docker",
          "description: Investigating Docker and Compose: whether containers are alive and restarting, following their logs, resources and disk, and reading a Compose setup.",
          "---",
          "",
          "# Investigating Docker (containers, Compose)",
          "",
          "## The whole picture first",
          "- Everything, stopped ones included: `docker ps -a` (read STATUS for Restarting / Exited",
          "  and the exit code)",
          "- The daemon: `systemctl status docker`",
          "- What it is using: `docker system df` (images, containers, volumes)",
          "",
          "## Dying, or restarting in a loop",
          "1. Which container: STATUS in `docker ps -a`. An Exited code, or Restarting, is the lead.",
          "2. Logs: `docker logs --tail 200 <name>` (narrow with tail if there are many; copy across",
          "   and use run_local if you need counts).",
          "3. What it looked like just before: `docker inspect <name>` (RestartCount, OOMKilled,",
          "   ExitCode, Health). OOMKilled true means it hit its memory limit.",
          "",
          "## Resources",
          "- What the running ones use: `docker stats --no-stream` (CPU, memory, I/O)",
          "- On the host: `df -h` (the volume `/var/lib/docker` is on), `free -m`",
          "",
          "## Eating the disk",
          "- `docker system df -v` for the breakdown. Clean up what is unused only after asking the",
          "  operator (**make sure a delete can be undone first, and leave volumes alone**).",
          "",
          "## Compose",
          "- Where it runs from: `docker compose ls`",
          "- The setup: read the project's `docker-compose.yml` / `compose.yaml` (services, ports,",
          "  volumes, environment).",
          "- **Never copy out a password or a token from the environment or from a file.**",
          "",
          "## Before changing anything",
          "- Say what recreating, deleting, pruning or touching a volume affects before you do it.",
          "- Check what depends on a container before stopping it (whether another one talks to it).",
          "",
        ]),
      },
      {
        name: "docker-crashloop",
        description:
          "Exit code, restart count and logs — including OOM",
        goal:
          "Look into the containers that are dying or restarting in a loop. Use docker ps -a and docker inspect for the exit code, RestartCount and OOMKilled, and get a first idea of the cause from the logs.",
        body: md([
          "---",
          "name: docker-crashloop",
          "description: Exit code, restart count and logs — including OOM",
          "goal: Look into the containers that are dying or restarting in a loop. Use docker ps -a and docker inspect for the exit code, RestartCount and OOMKilled, and get a first idea of the cause from the logs.",
          "---",
          "",
          "# Exit code, restart count and logs — including OOM",
          "",
          "Read the `docker` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Look into the containers that are dying or restarting in a loop. Use docker ps -a and docker inspect for the exit code, RestartCount and OOMKilled, and get a first idea of the cause from the logs.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "docker-list",
        description:
          "Which are alive, and what they are using",
        goal:
          "List which containers are running and which are stopped, and summarise the state of each and what it is using (CPU, memory).",
        body: md([
          "---",
          "name: docker-list",
          "description: Which are alive, and what they are using",
          "goal: List which containers are running and which are stopped, and summarise the state of each and what it is using (CPU, memory).",
          "---",
          "",
          "# Which are alive, and what they are using",
          "",
          "Read the `docker` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> List which containers are running and which are stopped, and summarise the state of each and what it is using (CPU, memory).",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "docker-disk",
        description:
          "The breakdown across images, containers and volumes",
        goal:
          "Find out what is making Docker eat the disk. Break it down with docker system df -v and show me what is using the space. Do not delete anything.",
        body: md([
          "---",
          "name: docker-disk",
          "description: The breakdown across images, containers and volumes",
          "goal: Find out what is making Docker eat the disk. Break it down with docker system df -v and show me what is using the space. Do not delete anything.",
          "---",
          "",
          "# The breakdown across images, containers and volumes",
          "",
          "Read the `docker` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Find out what is making Docker eat the disk. Break it down with docker system df -v and show me what is using the space. Do not delete anything.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "docker-compose",
        description:
          "Services, ports and dependencies from the compose file (secrets stay hidden)",
        goal:
          "Check the Docker Compose setup on this machine. Read the services, ports and dependencies from the compose file. Do not copy out environment values or passwords.",
        body: md([
          "---",
          "name: docker-compose",
          "description: Services, ports and dependencies from the compose file (secrets stay hidden)",
          "goal: Check the Docker Compose setup on this machine. Read the services, ports and dependencies from the compose file. Do not copy out environment values or passwords.",
          "---",
          "",
          "# Services, ports and dependencies from the compose file (secrets stay hidden)",
          "",
          "Read the `docker` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Check the Docker Compose setup on this machine. Read the services, ports and dependencies from the compose file. Do not copy out environment values or passwords.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
    ],
  },

  {
    id: "postgres",
    name: "PostgreSQL",
    summary: "Cannot connect, slow, or eating the disk — where to look in PostgreSQL.",
    stack: ["postgres", "postgresql", "pgsql"],
    skills: [
      {
        name: "postgres",
        description:
          "Investigating PostgreSQL: whether it is alive and reachable, slow queries and waits, connection counts, disk and logs.",
        body: md([
          "---",
          "name: postgres",
          "description: Investigating PostgreSQL: whether it is alive and reachable, slow queries and waits, connection counts, disk and logs.",
          "---",
          "",
          "# Investigating PostgreSQL",
          "",
          "Connecting needs credentials. **Ask the operator for the password. Do not copy out any",
          "setting you read.** A connection usually looks like `sudo -u postgres psql -c '...'`",
          "(authentication differs by machine; peer is common).",
          "",
          "## Start with",
          "- Alive: `systemctl status postgresql`",
          "- Reachable: `sudo -u postgres psql -c 'select 1;'` (adjust to the machine)",
          "- Where the configuration is: `SHOW config_file;`, `SHOW data_directory;`",
          "",
          "## Cannot connect",
          "- Is the service up, and listening on its port (5432 by default): `ss -ltnp | grep 5432`",
          "- Authentication: `pg_hba.conf` (which hosts, users and methods are allowed). The error",
          "  appears in the server log.",
          "- The connection limit: `SHOW max_connections;` against the current count (below).",
          "",
          "## Slow, or waiting",
          "- What is running now:",
          "  `SELECT pid, state, wait_event_type, now()-query_start AS dur, left(query,80) FROM pg_stat_activity ORDER BY dur DESC;`",
          "- Lock waits: line `pg_locks` up against `pg_stat_activity`.",
          "- Habitually slow queries: if `pg_stat_statements` is installed, by total time.",
          "",
          "## Connection counts",
          "- `SELECT count(*), state FROM pg_stat_activity GROUP BY state;`",
          "- A lot of idle in transaction points at uncommitted work on the application side.",
          "",
          "## Disk",
          "- Per database: `SELECT datname, pg_size_pretty(pg_database_size(datname)) FROM pg_database ORDER BY pg_database_size(datname) DESC;`",
          "- On the host: `df -h` (the volume data_directory is on). Watch for WAL (`pg_wal`) piling",
          "  up as well.",
          "",
          "## Logs",
          "- The location is `SHOW log_directory;` and `log_filename` (often under data_directory).",
          "- Narrow a large log with tail/grep, and copy it across for run_local if you need counts.",
          "",
          "## Before changing anything",
          "- To change a setting (postgresql.conf / pg_hba.conf), read the relevant part and show",
          "  what would change. Tell apart what a reload covers from what needs a restart. Say what",
          "  a VACUUM or a restart affects before you do it.",
          "",
        ]),
      },
      {
        name: "postgres-connect",
        description:
          "The service, the port, pg_hba and the connection limit",
        goal:
          "Find out why PostgreSQL will not accept a connection. Look at whether the service is alive and on its port, at the authentication in pg_hba.conf, and at the connection limit. Ask me for the password.",
        body: md([
          "---",
          "name: postgres-connect",
          "description: The service, the port, pg_hba and the connection limit",
          "goal: Find out why PostgreSQL will not accept a connection. Look at whether the service is alive and on its port, at the authentication in pg_hba.conf, and at the connection limit. Ask me for the password.",
          "---",
          "",
          "# The service, the port, pg_hba and the connection limit",
          "",
          "Read the `postgres` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Find out why PostgreSQL will not accept a connection. Look at whether the service is alive and on its port, at the authentication in pg_hba.conf, and at the connection limit. Ask me for the password.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "postgres-slow",
        description:
          "The heavy and waiting queries in pg_stat_activity",
        goal:
          "Find out why PostgreSQL is slow. Use pg_stat_activity for long-running queries, waits and locks, and narrow down where the slowness comes from.",
        body: md([
          "---",
          "name: postgres-slow",
          "description: The heavy and waiting queries in pg_stat_activity",
          "goal: Find out why PostgreSQL is slow. Use pg_stat_activity for long-running queries, waits and locks, and narrow down where the slowness comes from.",
          "---",
          "",
          "# The heavy and waiting queries in pg_stat_activity",
          "",
          "Read the `postgres` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Find out why PostgreSQL is slow. Use pg_stat_activity for long-running queries, waits and locks, and narrow down where the slowness comes from.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "postgres-connections",
        description:
          "Connections by state, and idle in transaction",
        goal:
          "Check PostgreSQL's connections by state and tell me whether anything is wrong — idle in transaction piling up, for instance.",
        body: md([
          "---",
          "name: postgres-connections",
          "description: Connections by state, and idle in transaction",
          "goal: Check PostgreSQL's connections by state and tell me whether anything is wrong — idle in transaction piling up, for instance.",
          "---",
          "",
          "# Connections by state, and idle in transaction",
          "",
          "Read the `postgres` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Check PostgreSQL's connections by state and tell me whether anything is wrong — idle in transaction piling up, for instance.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
      {
        name: "postgres-disk",
        description:
          "Size per database, and whether WAL is piling up",
        goal:
          "Find out how much disk PostgreSQL is using. Check the size of each database, whether WAL is piling up, and how much room is left on the host.",
        body: md([
          "---",
          "name: postgres-disk",
          "description: Size per database, and whether WAL is piling up",
          "goal: Find out how much disk PostgreSQL is using. Check the size of each database, whether WAL is piling up, and how much room is left on the host.",
          "---",
          "",
          "# Size per database, and whether WAL is piling up",
          "",
          "Read the `postgres` skill first: it says where things live on this machine and how to get",
          "at them without guessing a path.",
          "",
          "What is being asked:",
          "",
          "> Find out how much disk PostgreSQL is using. Check the size of each database, whether WAL is piling up, and how much room is left on the host.",
          "",
          "Say what you could not read and why. Never copy a credential into a summary or a report.",
          "",
        ]),
      },
    ],
  },
];
